### PR TITLE
Async

### PR DESCRIPTION
**Pull request by yzanhua**

### CODE REVIEW

**Comment by wkliao** [comment]
Please add a description about this PR.

**Review by wkliao — COMMENTED** [review]
If this is the error in Cache/Sync VOL, then create a PR in their repo.

**Review by wkliao — COMMENTED** [review]
Using MPI_Init_thread may be slower than MPI_Init and thus affects all other drivers.
I suggest to create a configure option to use MPI_Init_thread and make MPI_Init default.

**Review by wkliao — COMMENTED** [review]
This commit needs more information on how and where the pseudo computation is implemented and performs.

**Comment by khou2020** [comment]
> Using MPI_Init_thread may be slower than MPI_Init and thus affects all other drivers. I suggest to create a configure option to use MPI_Init_thread and make MPI_Init default.

Should it be a config option or command line option, or just enable when pseudo computation is enabled?

**Comment by wkliao** [comment]
The new run command-line option to specify the pseudo computation can be added
no matter if users run with Cache/Async VOLs. Default is disabled, i.e. no sleep.

A new configure option should be added, so we know users intend to run
Cache/Async VOLs, and thus call MPI_Init_thread.

**Comment by wkliao** [comment]
May be `--enable-threading`.

**Comment by khou2020** [comment]
This PR was for merging forked asyn branch into async branch
Recreate PR for merging into master: https://github.com/Parallel-NetCDF/E3SM-IO/pull/156

**Comment by khou2020** [comment]
#156 Merged.

**Pull request closed without merging**
