### PR TITLE
Add a few more 2D variables to F case study

### PR DESCRIPTION
**Pull request by dqwu**
This is a minor update to reflect latest E3SM changes to its F case.

### CODE REVIEW

**Comment by wkliao** [comment]
Hi @dqwu 
Could you please also update README,md to reflect the numbers of additional variables?

**Comment by dqwu** [comment]
@wkliao 
I have updated f_case_h0.txt and README.md.

**Comment by wkliao** [comment]
Please also update the below sentence in README.md. 382->388, and 317->323.
Everything else looks well. Thanks.
```
The F case uses three unique data decomposition patterns shared by 382 2D and
3D variables (2 sharing Decomposition 1, 317 sharing Decomposition 2, and
63 sharing Decomposition 3). 
```

**Comment by dqwu** [comment]
@wkliao 
README.md updated.

**Pull request merged**
