### PR TITLE
Add G case scorpio for ADIOS2 blob:

### PR DESCRIPTION
**Pull request by khou2020**
Assume G case scorpio strategty same as F case

### CODE REVIEW

**Comment by khou2020** [comment]
> Please add comments about which process is writing what metadata when ADIOS API is used.
> Either in source codes or README.md

I did. Every Scorpio data objects are commented.

**Comment by wkliao** [comment]
I did not see a general description about what metadata is written by root and 1st subfile,
and what are written by other processes and other subfiles. If you have that already,
point it out to me.

We need to proved a general rule for who writes what and later for who reads what.

**Comment by khou2020** [comment]
> I did not see a general description about what metadata is written by root and 1st subfile,
> and what are written by other processes and other subfiles. If you have that already,
> point it out to me.
> 
> We need to proved a general rule for who writes what and later for who reads what.

It is mostly in e3sm_io_case_scorpio.hpp. Most attributes only written by rank 0 is associated with a variable.
Only one additional variables are written by rank 0 only, it is at var_io_F_case_scorpio.cpp:575.

**Comment by wkliao** [comment]
There merely any comments in e3sm_io_case_scorpio.hpp and var_io_F_case_scorpio.cpp.
We need a better description in one place. Let's use var_io_F_case_scorpio.cpp.
Please draft one and I will help revise.

**Comment by khou2020** [comment]
> There merely any comments in e3sm_io_case_scorpio.hpp and var_io_F_case_scorpio.cpp.
> We need a better description in one place. Let's use var_io_F_case_scorpio.cpp.
> Please draft one and I will help revise.

done

**Comment by wkliao** [comment]
Please point out the description you added to me.
I was expecting the description added at the very top of the files
var_io_G_case_scorpio.cpp

The same for var_io_F_case_scorpio.cpp

**Comment by khou2020** [comment]
> Please point out the description you added to me.
> I was expecting the description added at the very top of the files
> var_io_G_case_scorpio.cpp
> 
> The same for var_io_F_case_scorpio.cpp

Moved to the top.

**Pull request merged**
