### PR TITLE
Minor change to blob method

### PR DESCRIPTION
**Pull request by khou2020**
Remove memory usage report.
Remove wait time report.
Rename _pio to _scorpio.

### CODE REVIEW

**Comment by wkliao** [comment]
This PR failed with compilation error below, when building without ADIOS.
```
  CXX      var_io_F_case.o
In file included from var_io_F_case.cpp:26:
../../src/drivers/e3sm_io_driver_adios2.hpp:15:10: fatal error: adios2_c.h: No such file or directory
 #include <adios2_c.h>
          ^~~~~~~~~~~~
compilation terminated.
make[4]: *** [Makefile:396: var_io_F_case.o] Error 1
```

**Comment by wkliao** [comment]
This should be fixed in 123004b4a190adf03752037150c765d32881c1c1
Please check.

README.md has instructions for building PnetCDF and HDF5.
It should also contain one for ADIOS.

**Comment by khou2020** [comment]
Dear Professor Liao:

Should it be rebased into that particular commit?
It was already merged. Rebasing will create a merge node in the master branch.

Respectfully yours,
kaiyuan

**Comment by wkliao** [comment]
No need to rebase.
Update your local copy of master branch and test if it can be built with and without ADIOS features.

**Pull request merged**
