### PR TITLE
Update for recent changes to log-based VOL

### PR DESCRIPTION
**Pull request by khou2020**
Use H5S_BLOCK if available.
Use H5Pset_buffered if available.

### CODE REVIEW

**Comment by wkliao** [comment]
github actions failed
Check the log files for error messages.

**Comment by khou2020** [comment]
> github actions failed
> 
> Check the log files for error messages.

I did but there is no log generated.

I will rebuild it on top of master.

**Comment by wkliao** [comment]
There are.
See https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true

Here are the error messages.
```
src/e3sm_io -k -a hdf5_log -r 2 -x log -y 2 -o ./test_output/hdf5_log_log_f_case_866x72_16p.h5 ./datasets/f_case_866x72_16p.h5
[611](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:611)
HDF5-DIAG: Error detected in HDF5 (1.13.0) MPI-process 0:
[612](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:612)
  #000: H5Sselect.c line 1673 in H5Sget_select_type(): not a dataspace
[613](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:613)
    major: Object ID
[614](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:614)
    minor: Unable to find ID information (already closed?)
[615](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:615)
HDF5-DIAG: Error detected in HDF5 (1.13.0) MPI-process 0:
[616](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:616)
  #000: H5S.c line 848 in H5Sget_simple_extent_ndims(): not a dataspace
[617](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:617)
    major: Invalid arguments to routine
[618](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:618)
    minor: Inappropriate type
[619](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:619)
[fv-az33-410:64065] *** An error occurred in MPI_Type_create_subarray
[620](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:620)
[fv-az33-410:64065] *** reported by process [2617049089,0]
[621](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:621)
[fv-az33-410:64065] *** on communicator MPI_COMM_WORLD
[622](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:622)
[fv-az33-410:64065] *** MPI_ERR_COUNT: invalid count argument
[623](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:623)
[fv-az33-410:64065] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[624](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:624)
[fv-az33-410:64065] ***    and potentially your MPI job)
[625](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:625)
FAIL test.sh (exit status: 2)
[626](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:626)
```

**Comment by khou2020** [comment]
> There are. See https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true
> 
> Here are the error messages.
> 
> ```
> src/e3sm_io -k -a hdf5_log -r 2 -x log -y 2 -o ./test_output/hdf5_log_log_f_case_866x72_16p.h5 ./datasets/f_case_866x72_16p.h5
> [611](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:611)
> HDF5-DIAG: Error detected in HDF5 (1.13.0) MPI-process 0:
> [612](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:612)
>   #000: H5Sselect.c line 1673 in H5Sget_select_type(): not a dataspace
> [613](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:613)
>     major: Object ID
> [614](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:614)
>     minor: Unable to find ID information (already closed?)
> [615](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:615)
> HDF5-DIAG: Error detected in HDF5 (1.13.0) MPI-process 0:
> [616](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:616)
>   #000: H5S.c line 848 in H5Sget_simple_extent_ndims(): not a dataspace
> [617](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:617)
>     major: Invalid arguments to routine
> [618](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:618)
>     minor: Inappropriate type
> [619](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:619)
> [fv-az33-410:64065] *** An error occurred in MPI_Type_create_subarray
> [620](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:620)
> [fv-az33-410:64065] *** reported by process [2617049089,0]
> [621](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:621)
> [fv-az33-410:64065] *** on communicator MPI_COMM_WORLD
> [622](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:622)
> [fv-az33-410:64065] *** MPI_ERR_COUNT: invalid count argument
> [623](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:623)
> [fv-az33-410:64065] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
> [624](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:624)
> [fv-az33-410:64065] ***    and potentially your MPI job)
> [625](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:625)
> FAIL test.sh (exit status: 2)
> [626](https://github.com/Parallel-NetCDF/E3SM-IO/runs/6280998228?check_suite_focus=true#step:14:626)
> ```

Looks like a bug in logvol 1.2.0. Will retry after logvol 1.3.0 release.

**Comment by wkliao** [comment]
Use this failure case to test log vol,
before log vol 1.3.0 can be released.

**Comment by wkliao** [comment]
add here v a reference to the fix commit

**Comment by khou2020** [comment]
> add here a reference to the fix commit



> add here a reference to the fix commit

It is caused by 1.2.0 doesn't recognize H5S_BLOCK.
E3SM sees H5S_BLOCK in HDF5 1.13.0 and used it.

The fix is the PR currently pending. 
commit 11a33529a757a4a6947268920bb4384031d6a2e9

**Comment by wkliao** [comment]
That is a big commit.
Please be more specific.

**Comment by wkliao** [comment]
There is no explanation on how this bug is resolved.
Commit and PR comments need to be more informative.
Your response and comments are not helpful.

**Comment by khou2020** [comment]
> 
E3SM sees H5S_BLOCK in HDF5 1.13.0 so it uses it instead of H5S_CONTIG.
However, logvol 1.2.0 does not recognize H5S_BLOCK as a special value and handled it as a traditional dataspace ID.
H5S_BLOCK is not considered a valid dataspace ID, so H5S routine does not accept it and returns error.

Logvol 1.3.0 can recognize both H5S_BLOCK and H5S_CONTIG, so it handled it correctly.
It is the result of adding support to H5S_BLOCK, not a fix to the algorithm.

**Comment by wkliao** [comment]
A PR should not break when using log vol 1.2.0.
Fix this PR, so E3SM-IO can still work with the older versions of log vol.

**Pull request merged**
