### PR TITLE
Fix errors in distcheck

### PR DESCRIPTION
**Pull request by khou2020**
Add m4 files to EXTRA_DIST
Disable HDF5 canonical test.

### CODE REVIEW

**Comment by wkliao** [comment]
About the comments of the 2nd commit.
```
Remove HDF5 multi-dataset test in make check:
H5Dwrite_multi does not support chunked datasets.
Disable HDF5 canonical support until the feature is supported
```
Do you mean the HDF5 multi-dataset does not support writing to
record variables? 

@qiaok ?

A solution is to use fixed-size datasets.
This should be fine for E3SM-IO benchmark, as the number of
records is set at the command line.

**Comment by khou2020** [comment]
> About the comments of the 2nd commit.
> 
> ```
> Remove HDF5 multi-dataset test in make check:
> H5Dwrite_multi does not support chunked datasets.
> Disable HDF5 canonical support until the feature is supported
> ```
> 
> Do you mean the HDF5 multi-dataset does not support writing to
> record variables?
> 
> @QiaoK ?
> 
> A solution is to use fixed-size datasets.
> This should be fine for E3SM-IO benchmark, as the number of
> records is set at the command line.

Will it be fair to other APIs?

**Comment by wkliao** [comment]
It has to be done under the current limitation,
but we will put a note for this.
So, please add the option back.

**Comment by khou2020** [comment]
> It has to be done under the current limitation,
> but we will put a note for this.
> So, please add the option back.

The option is not removed in E3SM. It is just excluded from make check tests.
The fix to make HDF5 work should be a different PR.

**Comment by wkliao** [comment]
If hdf5_md is not working, then there is no need to remove the tests
from parallel_runs.sh and seq_runs.sh. Keep them there.

**Comment by khou2020** [comment]
> If hdf5_md is not working, then there is no need to remove the tests
> from parallel_runs.sh and seq_runs.sh. Keep them there.

fixed

**Pull request merged**
