### PR TITLE
rework test script:

### PR DESCRIPTION
**Pull request by khou2020**
Merge seq_run and parallel_run
Replace expanded case and API options with loops and lists so new cases
and APIs can be added easily
Move test output files into a single folder so make clean only need to
delete the folder

### CODE REVIEW

**Comment by wkliao** [comment]
Can this be part of existing E3SM-IO/seq_runs.sh?

**Comment by khou2020** [comment]
It is a replacement of seq_runs.sh. seq_runs is no longer used.

**Comment by wkliao** [comment]
Why replace the original one?

**Comment by khou2020** [comment]
The new one is easier to maintain.
I will delete it if you don't like.

**Comment by wkliao** [comment]
Need more information about "easier to maintain".

A PR should describe what has been changed, new added, and old deleted.
This PR contains too little information.

**Comment by khou2020** [comment]
fixed

**Pull request merged**
