### PR TITLE
bugfix: cast str_att buffer to void* to avoid compile error on some strict compilers

### PR DESCRIPTION
**Pull request by khou2020**
Explicitly cast of const char* to void* to work around compiler type check.

### CODE REVIEW

**Comment by wkliao** [comment]
changes are not visible on the browser due to tab space.

**Comment by khou2020** [comment]
> changes are not visible on the browser due to tab space.

fixed.

**Comment by wkliao** [comment]
Make this 2 commits
First contains only white space changes.
Second contains the real fix.

**Comment by wkliao** [comment]
Github action failed after merging this PR to master.

**Comment by khou2020** [comment]
> Github action failed after merging this PR to master.

That is due a different bug independent to this one. I am still looking into it. Sometimes, fts_open will return file not found.

**Pull request merged**
