### PR TITLE
Add new case that mimic the I/O strategy of the scorpio module in E3SM F case

### PR DESCRIPTION
**Pull request by khou2020**
Simulate raw decomposition map when reading parsed decomposition file; Add command line option of I/O strategy (native/pio); Record dimensions as scalar variables instead of attribute in adios2 driver to match the behavior of scorpio;

### CODE REVIEW

**Comment by wkliao** [comment]
This "Simulate raw decomposition map" looks like a reverse engineering to me.
Maybe we can add an option to dat2nc.c to produce the nc file for that purpose.
At least, your changes to read_decomp.c should be guarded by a flag when Scorpio
type of I/O is chosen.

**Comment by khou2020** [comment]
> This "Simulate raw decomposition map" looks like a reverse engineering to me.
> Maybe we can add an option to dat2nc.c to produce the nc file for that purpose.
> At least, your changes to read_decomp.c should be guarded by a flag when Scorpio
> type of I/O is chosen.

The algorithm basically do nc2dat.
Do you mean configure flag? Should this part be an optional build?

**Comment by wkliao** [comment]
I meant `if (cfg->strate == pio)`

Also, using  keywords 'pio' and 'native' is kind of misleading.
Names of I/O strategies should be 'canonical', 'log', or 'blob'

**Comment by khou2020** [comment]
> I meant `if (cfg->strate == pio)`
> 
> Also, using keywords 'pio' and 'native' is kind of misleading.
> Names of I/O strategies should be 'canonical', 'log', or 'blob'

fixed

**Comment by wkliao** [comment]
'log' is for our log-based VOL
'blob' is for PIO's style, which is not a log-based.

**Comment by khou2020** [comment]
> 'log' is for our log-based VOL
> 'blob' is for PIO's style, which is not a log-based.

scorpio is a testcase. Should the option be mixed with API?
It will expand to 12 choice. {canonical, blob} * {pnc, hdf5, hdf5_multidset, hdf5_logvol, bp3, bp4}

**Comment by wkliao** [comment]
The names are for readability.
I/O strategies are not I/O methods.
We do not have to implement all combinations, but
must check the combination availability.

**Comment by khou2020** [comment]
> The names are for readability.
> I/O strategies are not I/O methods.
> We do not have to implement all combinations, but
> must check the combination availability.

fixed

**Pull request merged**
