### PR TITLE
rec extend for logvol API

### PR DESCRIPTION
**Pull request by khou2020**
Logvol also need E3SM to explicitly set dataset extent before writing records.

### CODE REVIEW

**Comment by wkliao** [comment]
Does this affect results we collected before? (timing, data amount, file size, etc.)

**Comment by khou2020** [comment]
> Does this affect results we collected before? (timing, data amount, file size, etc.)

No. It does not affect any write result. Only replay write will fail because dataset size not properly extended.

**Comment by wkliao** [comment]
In that case, please add Log VOL replay into test.sh and see if there are other failures.

**Comment by khou2020** [comment]
> In that case, please add Log VOL replay into test.sh and see if there are other failures.

It works on my side. I will retest that PR once this is merged.

**Comment by wkliao** [comment]
Just add it in this PR.

**Comment by khou2020** [comment]
> Just add it in this PR.

It also requires other logvol fixes not in 1.3.0 to pass the test.

**Comment by wkliao** [comment]
Because of the bug found in this PR, E3SM-IO now requires Log VOL version 1.4.0 and later.

**Pull request merged**
