### PR TITLE
Add git action

### PR DESCRIPTION
**Pull request by khou2020**
Add support for make check
Add git action to run make check

### CODE REVIEW

**Comment by wkliao** [comment]
```
  CXX      header_def_F_case.o
113
header_def_F_case.cpp: In member function ‘int e3sm_io_case::def_F_case(e3sm_io_config&, e3sm_io_decom&, e3sm_io_driver&, int)’:
114
header_def_F_case.cpp:153:5: note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
115
  153 | int e3sm_io_case::def_F_case(e3sm_io_config &cfg,
116
      |     ^~~~~~~~~~~~
117
header_def_F_case.cpp:153:5: note: variable tracking size limit exceeded
```

Please add `-fvar-tracking-assignments` to CFLAGS to configure command
and see if errors go away.

**Comment by wkliao** [comment]
FYI. I used this command.
```
make -s V=1 LIBTOOLFLAGS=--silent \
    distcheck \
    DISTCHECK_CONFIGURE_FLAGS="--with-pnetcdf=$SCRATCH/PnetCDF/dest CC=mpicc CXX=mpicxx CFLAGS=-fno-var-tracking-assignments CXXFLAGS=-fno-var-tracking-assignments"
```

**Comment by khou2020** [comment]
Dear Professor Liao:

It compiles with the flags, but I am getting error on make distcheck.
Ncmpi_create returns NC_EACCESS when writing test files.
I set the output file to e3sm_io.nc next to the benchmark program.
Seems make distcheck does not allow writing anything to the test folder.

Respectfully yours,
Kaiyuan

**Comment by wkliao** [comment]
You are using your dev branch to create this PR.
Please use a new branch instead.

**Comment by wkliao** [comment]
The github action should be a PR by itself.
Please keep the new make check a separate PR.

**Pull request closed without merging**
