### PR TITLE
Fix compile errors on xl compiler

### PR DESCRIPTION
**Pull request by khou2020**
Do not enable c++17 if compiler does not support
Do not add -std flag to CPPFLAGS

### CODE REVIEW

**Comment by wkliao** [comment]
This PR contains part of #112.

Also, have you tested the changes to configure.ac using compilers other than xl?

**Comment by khou2020** [comment]
> This PR contains part of #112.
> 
> Also, have you tested the changes to configure.ac using compilers other than xl?

Fixed.

I tested it locally with gnu compilers.

**Comment by wkliao** [comment]
Also test it on Cori.

**Comment by khou2020** [comment]
> Also test it on Cori.

tested without problem.

**Pull request merged**
