### PR TITLE
Allow user to set input/output file name instead of only directory name

### PR DESCRIPTION
**Pull request by khou2020**
Add description to input files option
Add additional description to -i option
Update README file for the new help message
Add more run command examples to README file.

Remove hard coded file names from the code.
Remove internal function arguments related to hard coded file names.
Change variables' name to reflect the type of its content form directory name to file name.

### CODE REVIEW

**Comment by wkliao** [comment]
Use 'output_path' is better than 'output_file' or 'output_dir'
in README, printf for usage and timing results.
In README, we need to say in what combination command-line
options it means a file name, and others a folder name (i.e. ADIOS+blob).

**Comment by wkliao** [comment]
I assume option '-i' is used to evaluate parallel read performance.
It can be combined with '-R' option.
The same for '-o' and '-W'.

**Comment by khou2020** [comment]
> I assume option '-i' is used to evaluate parallel read performance.
> It can be combined with '-R' option.
> The same for '-o' and '-W'.

-R is for read, -i is not.
-i is for test of real datasets. E3SM will read in real data and use it in write test.
The test file is always -o.

**Comment by wkliao** [comment]
If you are not evaluating read performance, then there is no point of reading "real datasets".
I assume this option is for your compression experiment.

**Comment by khou2020** [comment]
> If you are not evaluating read performance, then there is no point of reading "real datasets".
> I assume this option is for your compression experiment.

Yes. It is used when the content of the data affects the performance.

**Comment by wkliao** [comment]
I still see no need to have both -i and -R.
Same for -o and -W

**Comment by khou2020** [comment]
> I still see no need to have both -i and -R.
> Same for -o and -W

If you want to run write test only with real data, you need to set -i and -o.
-i does not imply read test and -o does not imply write test.
The file to read in read test is set by -o not -i.
-i is only used to load real data.

**Comment by wkliao** [comment]
What is the difference between read and load?

**Comment by khou2020** [comment]
> What is the difference between read and load?

We don't measure performance when reading. Loading should always use PnetCDF.

**Comment by wkliao** [comment]
Still not clear about the difference

**Comment by khou2020** [comment]
> Still not clear about the difference



> Still not clear about the difference

If user want to test HDF5 with real data. It set -o to where HDF5 writes, and -i to where the netcdf datasets are.
If user want to test HDF5 read performance, it set -o to the HDF5 file just written and set -R. It -i is set, we assume the file to read is in PnetCDF format.

**Pull request closed without merging**
