### PR TITLE
Ecp

### PR DESCRIPTION
**Pull request by khou2020**
HDF5 and ADIOS22 support for ECP delivery.

### CODE REVIEW

**Comment by wkliao** [comment]
README.md needs to be updated with the information below.
1. build with configure with command-line options
2. HDF5 requirement and build instructions
3. ADIOS requirement and build instructions

Does this PR include feature of running the log-based VOL?

**Comment by wkliao** [comment]
Why is changing to C++ is necessary?

**Comment by khou2020** [comment]
C++ class and containers make it easier to implement and maintain driver interfaces for different API and cases.
ADIOS2 API is mainly for C++. The C binding contains less options and have few documentations.

**Comment by wkliao** [comment]
People often encounter compilation issues when using C++.
Have you tested this PR on different DOE machines and different OSs?
If some modules must be loaded first on a DOE machine, these instructions
need to be added to README.md.

**Comment by wkliao** [comment]
Explain what folders cases and drivers are for.

**Comment by wkliao** [comment]
README.md still contains instructions to use Makefile in "Compile command to build the executable of benchmark program, e3sm_io"

**Comment by wkliao** [comment]
> C++ class and containers make it easier to implement and maintain driver interfaces for different API and cases.
> ADIOS2 API is mainly for C++. The C binding contains less options and have few documentations.

All history of the original C files are gone.
Changing programming language is a bad practice of creating pull requests.

**Comment by khou2020** [comment]
Those files are moved into cases and drivers directory.
Cases directory contains the test code for F and G cases.
Driver directory contains the interface for different underlying APIs.

ADIOS2 is written in C++ and requires a more recent C++ version than E3SM IO. Any platform supporting adios2 should support E3SM I/O without special care.

**Pull request closed without merging**
