### PR TITLE
Add utility bpstat to count ADIOS2 output file size:

### PR DESCRIPTION
**Pull request by khou2020**
Sum up the size of all variables and attributes across all subfiles

### CODE REVIEW

**Comment by wkliao** [comment]
Please update the file utils/README.md for this new utility program.

**Comment by khou2020** [comment]
> Please update the file utils/README.md for this new utility program.

done

**Comment by wkliao** [comment]
not seeing it

**Comment by khou2020** [comment]
> not seeing it

fixed

**Pull request merged**
