### PR TITLE
Use real raw decomposition map

### PR DESCRIPTION
**Pull request by khou2020**
Option in dat2nd to include raw file offsets before merging.
Read raw file offsets form the decomposition file if available.
Otherwise, generate it as usual.

### CODE REVIEW

**Comment by wkliao** [comment]
We need more information about the new command-line option added to dat2nc.
When to use it and when not to.
Example ?
These need to be added to README.md

As for read_decomp.c, it is not clear what has been changed.
Comments about which driver should call it with arguments must be added.

**Comment by khou2020** [comment]
> We need more information about the new command-line option added to dat2nc.
> When to use it and when not to.
> Example ?
> These need to be added to README.md
> 
> As for read_decomp.c, it is not clear what has been changed.
> Comments about which driver should call it with arguments must be added.

updated the readme file.

read_decomp has nothing to do with driver. It scan the input file to determine what to read.

**Comment by wkliao** [comment]
> read_decomp has nothing to do with driver. It scan the input file to determine what to read.

If this is the case, then why modify it?
Not clear what has changed in read_decomp.c

**Comment by khou2020** [comment]
> > read_decomp has nothing to do with driver. It scan the input file to determine what to read.
> 
> If this is the case, then why modify it?
> Not clear what has changed in read_decomp.c

read_decomp will see if the nc file contains the raw decomposition map added by -r.
If there is not, it will expand offset and len pairs in the converted map to simulate raw decomposition map.
It does not need special care form the user and any driver.

**Comment by wkliao** [comment]
Only adios driver needs the raw decomposition map.
So, the function is used differently by different drivers.
Adding comments to that file can improve its readability,
helping other code developers to learn the usage of a
new feature. Please add proper comments.

**Comment by khou2020** [comment]
> Only adios driver needs the raw decomposition map.
> So, the function is used differently by different drivers.
> Adding comments to that file can improve its readability,
> helping other code developers to learn the usage of a
> new feature. Please add proper comments.

done

**Pull request merged**
