### PR TITLE
Add additional profiling timers

### PR DESCRIPTION
**Pull request by khou2020**
In ADIOS2 driver.
In e3sm_io_core.

### CODE REVIEW

**Comment by wkliao** [comment]
Have you run "make distcheck"? For example, I am using the following.
```
make distcheck DISTCHECK_CONFIGURE_FLAGS="--silent --with-pnetcdf=$SCRATCH/PnetCDF/1.12.2 --with-adios2=$SCRATCH/ADIOS/2.7.1 --with-hdf5=$SCRATCH/HDF5/1.12.0 CC=mpicc CXX=mpicxx"
```

**Comment by khou2020** [comment]
> Have you run "make distcheck"? For example, I am using the following.
> 
> ```
> make distcheck DISTCHECK_CONFIGURE_FLAGS="--silent --with-pnetcdf=$SCRATCH/PnetCDF/1.12.2 --with-adios2=$SCRATCH/ADIOS/2.7.1 --with-hdf5=$SCRATCH/HDF5/1.12.0 CC=mpicc CXX=mpicxx"
> ```

I got this error
configure: error: 
      -----------------------------------------------------------------------
      Missing PnetCDF-header files 'pnetcdf.h' required to build E3SM_IO. Use
      configure command-line option --with-pnetcdf=/path/to/implementation
      to specify the location of PnetCDF installation. Abort.
      -----------------------------------------------------------------------
make: *** [Makefile:984: distcheck] Error 1

It don't seems anything to do with the timers.

**Comment by wkliao** [comment]
You have to replace those paths for PnetCDF/HDF5 with your own paths.

**Comment by khou2020** [comment]
> You have to replace those paths for PnetCDF/HDF5 with your own paths.

I fixed them in later commits.
It is unrelated to the timers and will be in another PR.

**Pull request merged**
